version: '3'
services:
   flask_app:
      build: .
      command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
      env_file:
         - .env

   postgresql:
      image: postgres:latest
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=211217ns
         - POSTGRES_DB=schedulerdb